# packages/db/docker-compose.yml
version: "3.8"

services:
  mongo_spolka:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo_spolka_data:/data/db"
      - "mongo_spolka_config:/data/configdb"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=localhost
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8080:8081"

volumes:
  mongo_spolka_data:
  mongo_spolka_config:
